#!/bin/bash

source env/bin/activate

echo "Running black..."
black --exclude env . --line-length 120
echo "Running isort..."
isort . -s env
echo "Fixing implicit optional..."
no_implicit_optional carbondate
echo "Generating docs..."
pdoc3 carbondate --html -o docs --force --template-dir docs/templates
echo "Checking code quality..."
mypy carbondate
radon cc carbondate
pytest -lvv